include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_empty_else: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    unnecessary_statements: true
    avoid_unnecessary_containers: true
    # Prevents unnecessary allocation of a field
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_unused_constructor_parameters: true
    # Prevents leaks and code executing after their lifecycle.
    cancel_subscriptions: true
    constant_identifier_names: true
    unnecessary_string_interpolations: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_checks: true
    unnecessary_null_aware_assignments: true
    unnecessary_new: true
    unnecessary_brace_in_string_interps: true
    avoid_classes_with_only_static_members: false
    close_sinks: true
    #Prefer using ??= over testing for null.
    prefer_conditional_assignment: true
    #Use isEmpty for Iterables and Maps.
    prefer_is_empty: true
    #Use isNotEmpty for Iterables and Maps.
    prefer_is_not_empty: true
    #Only use double quotes for strings containing single quotes.
    require_trailing_commas: true
    always_declare_return_types: true
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    avoid_types_as_parameter_names: true
    avoid_redundant_argument_values: true
    camel_case_extensions: true
    camel_case_types: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    prefer_null_aware_operators: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_final: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    use_enums: true
    use_is_even_rather_than_modulo: true
