name: skin_match
description: A Job A Lots Flutter App

version: 0.0.2+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 3.3.1
  cupertino_icons: 1.0.6
  device_info_plus: 9.1.2
  dio: 5.4.1
  dropdown_button2: 2.3.9
  firebase_core: 3.1.1
  firebase_messaging: 15.0.2
  fluttertoast: 8.2.4
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.10+1
  fpdart: 1.1.0
  get: 4.6.6
  get_storage: 2.1.1
  http: 1.1.0
  image_picker: 1.0.7
  internet_connection_checker: 1.0.0+1
  intl: 0.19.0
  intl_phone_number_input: 0.7.4
  json_annotation: 4.8.1
  logger: 2.0.2+1
  mockito: 5.4.4
  path_provider: 2.1.2
  pin_code_fields: 8.0.0
  shared_preferences: 2.2.2
  auto_height_grid_view: 1.0.0
  flutter_onboarding_slider: 1.0.11
  smooth_page_indicator: 1.0.0
  file_picker: 7.1.0
  mime: 1.0.4

dev_dependencies:
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  get_it: 7.6.7

dependency_overrides:
  platform: 3.1.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

  #TODO: Add Font here if you extra added
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
    - family: ProductSansBold
      fonts:
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 600
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
          weight: 600
        - asset: assets/fonts/Product-Sans-Italic.ttf
          weight: 400
        - asset: assets/fonts/Product-Sans-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
