// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnN2iVzymjR79nNaJNjIDei7DOJcdBI0Y',
    appId: '1:352546152689:android:3407c9385cb902c3f7c950',
    messagingSenderId: '352546152689',
    projectId: 'skin-care-d6a4e',
    storageBucket: 'skin-care-d6a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwLk2mwvdou4YoZ0NSOK_7X_WkWbRtg0',
    appId: '1:352546152689:ios:0e478e7396aa6a6ef7c950',
    messagingSenderId: '352546152689',
    projectId: 'skin-care-d6a4e',
    storageBucket: 'skin-care-d6a4e.appspot.com',
    androidClientId: '352546152689-paav54opqk6p1fuq9t4r58ec7t7g74af.apps.googleusercontent.com',
    iosClientId: '352546152689-pdp0hpuaoimb9sl1jdq0qldeil3hnaoh.apps.googleusercontent.com',
    iosBundleId: 'com.jli.bargainfox.ImageNotification',
  );

}